### ISSUE TITLE
BUG:  Getting "Error: Cannot resolve type entity i4.SmpDomModule to symbol" when trying to add NgxPopperjsModule

### ISSUE THREAD

**Issue by ahujamoh** [tonysamperi/ngx-popperjs#27]
**NOTE**

**Describe the bug**

I was trying to integrate ngx-popperjs to my app. I am using node v14.18.1 (npm v6.14.15); typescript: 4.3.5

**To Reproduce**
When I install the packages using `npm install @popperjs/core ngx-popperjs --save`. After that I try to add the code to my app.module.ts

```ts
import {NgxPopperjsModule} from 'ngx-popperjs';

@NgModule({
 // ...
 imports: [
   // ...
   NgxPopperjsModule
 ]
})
```
As soon as I add the NgxPopperjsModule, I see the crash in logs, and ng build fails

**Expected behavior**
Crash should not happen in the logs and builds should go on successfully

**Crash Logs**

```sh
$MODULE_ROUTING_FILENAME - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i4.SmpDomModule to symbol
    at Object.reflectTypeEntityToDeclaration (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/reflection/src/typescript.js:482:19)
    at ${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/util.js:34:35
    at Array.map (<anonymous>)
    at Object.extractReferencesFromType (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/util.js:29:29)
    at DtsMetadataReader.getNgModuleMetadata (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/dts.js:63:33)
    at MetadataDtsModuleScopeResolver.resolve (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/dependency.js:61:43)
    at LocalModuleScopeRegistry.getExportedScope (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/local.js:515:51)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/local.js:257:44)
    at LocalModuleScopeRegistry.getScopeOfModule (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/local.js:148:22)
    at LocalModuleScopeRegistry.getScopeForComponent (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/local.js:122:22)
    at ComponentDecoratorHandler.resolve (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:499:42)
    at TraitCompiler.resolve (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:469:50)
    at ${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:656:31
    at ActivePerfRecorder.inPhase (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/perf/src/recorder.js:64:24)
    at NgCompiler.resolveCompilation (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:655:31)
    at NgCompiler.<anonymous> (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:522:54)



✖ Failed to compile.
⠋ Generating browser application bundles...(node:63303) UnhandledPromiseRejectionWarning: Error: Cannot resolve type entity i4.SmpDomModule to symbol
    at Object.reflectTypeEntityToDeclaration (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/reflection/src/typescript.js:482:19)
    at ${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/util.js:34:35
    at Array.map (<anonymous>)
    at Object.extractReferencesFromType (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/util.js:29:29)
    at DtsMetadataReader.getNgModuleMetadata (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/dts.js:63:33)
    at MetadataDtsModuleScopeResolver.resolve (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/dependency.js:61:43)
    at LocalModuleScopeRegistry.getExportedScope (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/local.js:515:51)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/local.js:257:44)
    at LocalModuleScopeRegistry.getScopeOfModule (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/local.js:148:22)
    at LocalModuleScopeRegistry.getScopeForComponent (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/scope/src/local.js:122:22)
    at ComponentDecoratorHandler.resolve (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:499:42)
    at TraitCompiler.resolve (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:469:50)
    at ${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:656:31
    at ActivePerfRecorder.inPhase (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/perf/src/recorder.js:64:24)
    at NgCompiler.resolveCompilation (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:655:31)
    at NgCompiler.<anonymous> (${PROJECTPATHIDDEN}/node_modules/@angular/compiler-cli/src/ngtsc/core/src/compiler.js:522:54)
(node:63303) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
⠙ Generating browser application bundles (phase: building)...(node:63303) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
```

**Versions :**
Angular CLI: 12.2.17
Node: 14.18.1
Package Manager: npm 6.14.15
OS: darwin x64

**Additional context (optional)**
I have not used systemjs up till now in my project. It is not clear in the documentation whether that is a necessity for this dependency to be added

**Comment by tonysamperi** [comment]
@ahujamoh  Please read carefully the issue template and compile all the required info

**Comment by peter-kiss-epam** [comment]
SmpDomModule is part of package https://www.npmjs.com/package/@ngx-tonysamperi/dom which unfortunately does not have source link. ngx-popperjs contains peer-dependecy to that package from 13.2.2.

**Comment by tonysamperi** [comment]
@peter-kiss-epam don't worry, the source of SmpDomModule is absolutely fine.
If you're having issues and setup a reproduction on Stackblitz let me know and I will take a look!

Cheers
